### ISSUE TITLE
Add Support for State Heterogeneity [FR]

### ISSUE THREAD

**Issue by SamuelGong** [TL-System/plato#101]
**Is your feature request related to a problem? Please describe.**

In cross-device practice, clients will join and leave from time to time, instead of staying online all the time. Moreover, their behaviors differ from one another, which is referred to as **state heterogeneity** in the literature [1, 2, 3]. We are thus interested in enhancing Plato with the support for emulating/simulating clients' variability in the available status.

**Describe the solution you'd like**

From our perspective, clients' dropout needs to be implemented in a programmatic way. For example, we can introduce the use of a predefined trace, of which each entry indicates the transition time of a particular client's availability. For example, an entry may look like

```
[client_id]: [starting status], [transition time (in seconds) t1, t2, ...]
e.g., 1: on, [54, 890, 2042, ...]
```

Of course, the trace can also be generated in a programmatic way, e.g., with each client's arrival following a Poison distribution, if appropriate. ***Thus, we anticipate that the generation of the availability traces can be added as a library*** in `~/packages`.

Then, with compatible parsing logic, Plato's runtime can be informed of clients' availability dynamics, and act accordingly. Specifically,

1. For **emulation** mode, instead of performing `start_clients()` in one go at the very beginning, we may want to make the action of `client starting` one kind of event that is triggered by time, following the loaded trace. Similarly, `client shutdown` may also be regarded as a time-driven event.

2. For simulation mode, it should be as simple as varying the set of selectable clients according to the trace, i.e., the major change of code might take place at the `select_clients()` or `choose_clients()` part.

**Major concern: it looks like we have to make a groundbreaking change, e.g., adding a new module as we do not think that this logic is a new kind of server/client/algorithm... We would like to listen to the authors' opinions if any. Thanks!**

**Additional context**

[1] C. Yang, Q. Wang, M. Xu, Z. Chen, K. Bian, Y. Liu, and X. Liu, [Characterizing Impacts of Heterogeneity in Federated Learning upon Large-Scale Smartphone Data](https://dl.acm.org/doi/abs/10.1145/3442381.3449851), in WWW, 2021.
[2] F. Lai, Y. Dai, X. Zhu, and M. Chowdhury, [FedScale: Benchmarking Model and System Performance of Federated Learning](https://arxiv.org/abs/2105.11367), in arXiv:2105.11367, 2021.
[3] Z. Jiang and W. Wang, [System Optimization in Synchronous Federated Training: A Survey](https://arxiv.org/abs/2109.03999), in arXiv:2109.03999, 2021.

**Comment by baochunli** [comment]
This is perhaps best implemented as an optional addition to the simulation mode, which is already supported in Plato and as you correctly pointed out, it should be relatively straightforward. Also, I don't really think one should start from something as sophisticated as playing back a trace -- For almost 100% of the research projects, using a simple random process to characterize client availability is good enough. After all, even if a trace can be replayed, such traces are hardly available from actual real-world environments.

**Comment by baochunli** [comment]
It looks like the FedScale git repo contains a raw 24.5 MB trace in binary format for the so-called 'device_info' -- FedScale/dataset/data/device_info/. It should be fairly straightforward to transfer the trace into more readable JSON formats for better parsing. 

Using JSON is perhaps a better choice than a proprietary format (such as '[client_id]: [starting status], [transition time (in seconds) t1, t2, ...] e.g., 1: on, [54, 890, 2042, ...]'), since it can be easily parsed using standard off-the-shelf parsers.

Reading from actual traces, however, should still come as a next feature after the use of simple random processes can be implemented, which is much more reproducible and adjustable (in terms of parameter settings) despite the fact that they are synthetic.

**Comment by SamuelGong** [comment]
I see. We are then going to start with random processes in the simulation mode. The reproducibility may be guaranteed by using consistent seeds for any random number generator.

**Comment by baochunli** [comment]
Yes, reproducibility is indeed guaranteed with a pre-specified random seed (which is already a configuration parameter).

**Comment by baochunli** [comment]
Closed due to low priority.
