### ISSUE TITLE
Add general data transfer protocol between client and server [FR]

### ISSUE THREAD

**Issue by crownk1997** [TL-System/plato#108]
**Is your feature request related to a problem? Please describe.**
In cross-platform cases,  it is highly possible for the client to support different AI frameworks with the server. In my case, the client side is Atlas500, which does not support any AI framework but NNRT. NNRT does not have the concept of tensor and it can only transfer representation features by using numpy array. However, on the server side, other AI frameworks, like Pytorch, expect the input should be Tensor where we need to transfer data type based on different frameworks. 

**Describe the solution you'd like**
It might be convenient for us to share a general data transfer protocol among tensorflow, pytorch, mindspore, nnrt and so on. For example, we can always transfer numpy array data type and perform data type transfer when the server side receives data,  no matter which kind of AI frameworks we use in the client side, 
```
protocol Myprotocol {
    data: extracted_features (numpy array),
    func CheckDataIntergrity(),
    func DataTypeTransfer() ... }
```

The DataTypeTransfer function will transform the data type from numpy array to the target AI platform.

**Comment by hcngac** [comment]
This can be viewed as a pre-requisite to issue #119, for providing a unified data exchange format, such that different data processors can be plugged into the data-exchange, not only for reformatting, but also for other features such as local differential privacy and model/feature compression.

**Comment by baochunli** [comment]
This can be quite easily achieved by converting framework-specific weights to numpy arrays in `Algorithm.extract_weights()` and `Algorithm.load_weights()`:

https://github.com/TL-System/plato/blob/c238f2d3a79d7eb18bb2178821de7fb3a25a37ec/plato/algorithms/mindspore/fedavg.py#L13-L25

https://github.com/TL-System/plato/blob/c238f2d3a79d7eb18bb2178821de7fb3a25a37ec/plato/algorithms/mindspore/fedavg.py#L32-L41

The only other location that requires a little bit of work to make sure `fedavg` works correctly is to implement the `trainer.zeros()` function to initialize a numpy-based zeros array. An example is shown in `trainers/mindspore/basic.py`:

https://github.com/TL-System/plato/blob/c238f2d3a79d7eb18bb2178821de7fb3a25a37ec/plato/trainers/mindspore/basic.py#L60-L64
