### ISSUE TITLE
[BUG] Ratio of stable parameters is always 0 in Adaptive Freezing

### ISSUE THREAD

**Issue by Ksld154** [TL-System/plato#143]
**Describe the bug**
The adaptive freezing example `(examples/adaptive_freezing)`  always show 0% stable parameters, 
even with incredibly large `stability_threshold` value (e.g. 0.9) and `random_freezing` turned on.
I think that probably all parameters on selected workers are misidentified as un-stable, and therefore sent to server to join training

**To Reproduce**
1. In `adaptive_freezing_CIFAR10_resnet18.yml`, set `rounds: 50`, `stability_threshold: 0.9`,  `random_freezing:true`
2. `python adaptive_freezing.py --config=./adaptive_freezing_CIFAR10_resnet18.yml `

**Expected behavior**
The stable parameters should be correctly identified and exclude from transmission

**Screenshots**

**OS environment (please complete the following information):**
 - OS:  Ubuntu 18.04
 - Environment: 
   - PyTorch 1.10.1
   - Python 3.9
   - CUDA 11.3

**Additional context**
After tracing code, I think that inside `adaptive_freezing_algorithm.py`,
function `update_sync_mask():` should be 
```python
self.wake_up_round[name] indices] = self.current_round + self.frozen_durations[name][indices]
self.sync_mask[name] = (self.wake_up_round[name] >= self.current_round)
```
Since that `sync_mask[name] == 1` indicate active parameters, which is opposite to `M_is-frozen` in your paper

But after this modification, the `Algorithm` object at server-side would get different `sync_mask[name]` from client-side which would cause some RuntimeError
In your version,  `sync_mask[name]` keeps to be `true` for all elements on both server and client, therefore might not have any error

**Comment by akyo1o** [comment]
Although this is an inspired paper, there are a lot of bugs in the current code including the Algorithm of this paper. I have spent two days running it successfully and the stable ratio is not again 0.

**Comment by baochunli** [comment]
The implementation of this algorithm has been moved to `/outdated` for reference, as it has not been updated to the latest Plato API.
