### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CQIITLAB** [TL-System/plato#146]
We tried 500 epochs and the test results are still zero. Then we checked the code and found that NMS was not used on line 310 of "Plato /trainers/yolo.py" and the shape of 'pred' in line 312 was different from the shape of 'pred' in the original Yolov5. After we retrain by adding NMS, the results of 100 and 300 epochs are as follows:
![image](https://user-images.githubusercontent.com/31148069/149057322-f63c9a7d-f310-445e-81ff-ea9fab18b783.png)

![image](https://user-images.githubusercontent.com/31148069/149058780-98ed5cde-a514-47ab-8f98-d0f718e8fefc.png)

**Comment by baochunli** [comment]
If you know what the issue is, could you please submit a PR as a fix?

**Comment by CQIITLAB** [comment]
I haven't figured out what the issue is yet. Trying to locate it
