### ISSUE TITLE
[RFC] In preparation for mobile clients

### ISSUE THREAD

**Issue by hcngac** [TL-System/plato#156]
- [ ] Isolation of project code and model data. Mobile app has to be packaged and be read-only. An option to choose where model and data be saved is recommended.
- [ ] Synchronized configuration loading. Mobile app cannot load config YAML from terminal. A simple HTTP server providing the configuration is recommended.
- [ ] Central logging facility. Logs from mobile client cannot be extracted easily for now. Use of log server is recommended.
- [ ] Removal of unsupported requirements. `datasets` and `zstd` is not currently supported. Either we trace all their requirements and build them (not practical) or we work around it by other means.

There can be other undiscovered roadblocks for mobile clients.
Not sure if these requirements call for redesign of the project structure. I'm not experienced in mobile development either so there can be other issues.

**Comment by baochunli** [comment]
Regardless of the approach, I was thinking that the mobile clients sound like a major undertaking. I am thinking that smaller projects should be attempted first, such as supporting secure multi-party computation (perhaps with the use of [CrypTen](https://github.com/facebookresearch/crypten) or something similar).

**Comment by hcngac** [comment]
Suppose we do SecureMPC on FedAvg, client-client communication is needed and it would also involve redesign?

**Comment by hcngac** [comment]
CrypTen uses `torch.distributed` as backend
