### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tianzheng4** [TL-System/plato#182]
**Describe the bug**
If I run the program with differential privacy, then there is a bug.

**To Reproduce**
1. Uncomment the lines following whether to apply differential privacy in `configs/EMNIST/fedavg_lenet5.yml`
![image](https://user-images.githubusercontent.com/28912159/169919673-8d89a7d6-b325-412d-be5a-bc3f04c17355.png)

2. Execute `./run -c configs/EMNIST/fedg_lenet5.yml` 

**Expected behavior**
The program should run smoothly without bug (I did not get any error before).

**Screenshots**
![image](https://user-images.githubusercontent.com/28912159/169919623-f7fccd20-c8aa-47b4-a4e6-7d564ff14392.png)

**OS environment (please complete the following information):**
 - OS: Ubuntu Linux

**Comment by baochunli** [comment]
Looks like downgrading to Opacus 1.1.1 will resolve this issue — something changed since that version.

**Comment by tianzheng4** [comment]
Downgrading to Opacus 1.1.1 resolves this issue.

**Comment by baochunli** [comment]
This issue is deeper than what it looks like. It appears that the current implementation is incorrect, and this is only exposed by Opacus 1.1.2. I am working towards a fix.

**Comment by baochunli** [comment]
Finished the fix to this issue.
