### ISSUE TITLE
[BUG] `tests/config_tests.py` `tests/data_tests.py` and `tests/sampler_tests.py` failed due to missing configuration files

### ISSUE THREAD

**Issue by baochunli** [TL-System/plato#190]
**Describe the bug**
Running `tests/config_tests.py` `tests/data_tests.py` and `tests/sampler_tests.py` failed due to missing configuration files:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/bli/plato/configs/Kinetics/Models/kinetics_full_models.yml'
```

**To Reproduce**

```
python tests/config_tests.py
python tests/sampler_tests.py
python tests/data_tests.py
```

**Expected behavior**

This unit test is expected to pass.

**OS environment (please complete the following information):**
 - OS: Ubuntu Linux
 - Version: 20.04 LTS

**Additional context**

PyLint errors also exist when statically checking this code. Such as attributes defined outside `__init__`, variable names do not conform to snake-case naming convention in PEP8, and missing method docstring. These PyLint errors need to be fixed as well as much as possible.

**Comment by CSJDeveloper** [comment]
I am going to fix it.
