### ISSUE TITLE
[RFC] Configuration of attribute in FedAsync

### ISSUE THREAD

**Issue by xuannn1998** [TL-System/plato#219]
Hi there, 

The attribute _**per_round**_ is set to 20 in `examples/fedasync/fedasync_MNIST_lenet5.yml`.
I thought there is no client selection mechanism in _FedAsync_. (paper: Asynchronous Federated Optimization)
Is my understanding wrong?

Thanks.

**Comment by baochunli** [comment]
`per_round` means the number of clients selected per communication round. A random selection mechanism will be used by default.

**Comment by xuannn1998** [comment]
Yes, I know the meaning of `per_round`.
But I thought FL (in asynchronous mode) do not use client selection mechanism?

**Comment by baochunli** [comment]
In asynchronous federated learning, the server still engages in client selection, and selects `per_round` number of clients in the first round. FedAsync proposed to aggregate as soon as one client arrives, and selects one more client to replace it.
