### ISSUE TITLE
[FR] Allowing different torch multiprocessing sharing strategies

### ISSUE THREAD

**Issue by dixiyao** [TL-System/plato#241]
**Is your feature request related to a problem? Please describe.**
I found we can let plato provide different choices for sharing strategies depending on users demands. When I was trying to train DARTS generated model on plato under FedAvg. It reports an error that: 
```
RuntimeError: unable to open shared memory object </torch_blabla> in read-write mode
```
Actually, this is not an error techniqually speaking. In torch official document, [sharing strategies](https://pytorch.org/docs/master/multiprocessing.html?highlight=sharing%20strategy#sharing-strategies) are introduced that the default strategy is *File descriptor*. However, it says that 
*Note that if there will be a lot of tensors shared, this strategy will keep a large number of file descriptors open most of the time. If your system has low limits for the number of open file descriptors, and you can’t raise them, you should use the file_system strategy.*
For example, the model I used here (though it does not need much GPU memory with certain batch size e.g., 1.7GB). However, it will raise such Runtime Error.
After I add 
```
torch.multiprocessing.set_sharing_strategy('file_system')
````
at the start of my customized main file. The problem can be solved as I change the sharing strategy into FileSystem. However, even if torch has ```torch_shm_manager``` to prevent shared memory leaks. It is still suggested that
*Still, if your system has high enough limits, and file_descriptor is a supported strategy, we do not recommend switching to this one.*

**Describe the solution you'd like**
1. add a new configuration setting under ```trainer.max_concurrency``` section, called ```file_system```. If it is true, plato execute ```torch.multiprocessing.set_sharing_strategy('file_system')```, other wise just set to the defualt.
2. If ```file_system``` is true, we should also raise a warning to users, indicating poential risks of shared memory leaks and suggest them that if the system has high enough limits, we should not use this sharing strategy.

**Describe alternatives you've considered**
We can just change the document. Add an item in Miscellaneous Notes.

**Comment by baochunli** [comment]
Rather than using `file_system` as the sharing strategy, I think this issue will go away relatively easily if you allocate more physical memory to your job, especially if you use a Docker container.
