### ISSUE TITLE
[RFC] Question about your implementation

### ISSUE THREAD

**Issue by hodatorabi** [TL-System/plato#274]
Hello,

Sorry if this is not the place for this to be asked, but I was reading your code and there is a part that I don't understand. I noticed that in the base server, base.py, it's the `_process_clients` method that takes care of determining whether it is time to process the client reports and proceed with the aggregation process, however, this is also being done in the `periodic_task` if I'm not wrong. Can you perhaps explain to me how these two are different? Thank you!

**Comment by baochunli** [comment]
Depending on `self.simulate_wall_time`, there are two ways of running Plato sessions in asynchronous mode. One is to run it in real-time, where `_periodic_task(self)` is called, and the other is to run it with the wall-clock time simulated, when `_periodic_task(self)` is not called. In the latter case, `_process_clients()` is where aggregation starts.
