### ISSUE TITLE
non iid data

### ISSUE THREAD

**Issue by Siminjv** [TL-System/plato#288]
Hi,
I want to change oort in a way that we using non iid data. I changed the sampler in yml file, but it had some errors. Plus, I'm gonna change using different data size for each client. Would you please explain how I can make a change in that?

Thanks

**Comment by Yufei-Kang** [comment]
Hi, we provide "noniid" sampler in "plato/plato/samplers" that samples data following the Dirichlet distribution. You can use it by setting `sampler: noniid` and`concentration: 1` in .yml file. For assigning different data size, "sample_quantity_noniid" sampler is provided in "plato/plato/samplers".

**Comment by Siminjv** [comment]
Hi,

unfortunately, I could not find concentration: 1 in samplers. Would you please let me know where i can find and change it.


Thanks
