### ISSUE TITLE
The server in the mistnetplus example still uses socket.send() rather than send() in the base server class.

### ISSUE THREAD

**Issue by baochunli** [TL-System/plato#88]
This may be problematic with virtual client IDs, used in simulated clients introduced in the current Plato release.

**Comment by XinYao1994** [comment]
Got it, I have updated it and make it work with the current release of Plato.

**Comment by XinYao1994** [comment]
Solved at 677b53b8b9738ad5ecbd37d438d6e5265d360bd6.
