### ISSUE TITLE
[BUG] packet queue is empty, aborting

### ISSUE THREAD

**Issue by XinYao1994** [TL-System/plato#96]
**Describe the bug**
I guess it is a mechanism, which detects some unused sockets and closes them.

**To Reproduce**
1. run mistnet-yolov5 example with several clients (4 in my case)
2. when the server uses the CPU to train the feature dataset, it usually needs a long time, and some clients will generate the bug message, which is similar to timeout.

**Expected behavior**
[INFO][05:12:15]: [Client # 4] Contacting the central server.
[INFO][05:12:15]: [Client # 4] Connecting to the server at http://172.18.0.2:30496.
[INFO][05:12:15]: [Client # 4] Connected to the server.
[INFO][05:12:15]: [Client # 4] Waiting to be selected.
packet queue is empty, aborting
[ERROR][06:12:20]: packet queue is empty, aborting

**OS environment (please complete the following information):**
 - Ubuntu
 - 20.04

**Comment by baochunli** [comment]
Please try to add `ping_timeout` in the `server` section in your configuration file. The default value for `ping_timeout` is `360` (seconds), try to set it to a longer and more appropriate value for your experiment.

**Comment by XinYao1994** [comment]
Thanks, it seems this parameter is necessary for all cases. Closed.
